apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 2
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: piomin/department
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: department
  labels:
    app: department
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: department